export default [
  // {
  //   "layout": "markdown-only",
  //   "format": "blog",
  //   "title": "My new journey just begun.",
  //   "description": "This is the my starting point for my future goals.",
  //   "slug": "my-new-solo-dev-journey",
  //   "published": "2024-12-22",
  //   "categories": ["story"],
  //   "type":"blog"
  // },
  {
    layout: 'markdown-term',
    format: 'playground',
    title: 'Webcontainers, wasm powered containers in your browser',
    description: 'Jump into wasm containers that could change the way we build web apps.',
    slug: 'webcontainers-on-your-browser',
    published: '2024-12-23',
    categories: ['webcontainers'],
    type: 'course',
  },
  {
    layout: 'markdown-snipp',
    format: 'snipp',
    title: 'Neubrutalist button sample with Tailwindcss',
    description: 'A simple button with neubrutalist style.',
    slug: 'tailcomp-1-button-neubrutalist',
    published: '2024-12-24',
    categories: ['tailwindcss'],
    type: 'snippet',
  },
  {
    layout: 'markdown-term',
    format: 'playground',
    title: 'jsc1: Express.js "Hello World" App /w Webcontainers',
    description: 'Nodejs Hands-on C1: Create a simple express nodejs app in your browser.',
    slug: 'node-js-1-webcontainers-hello',
    published: '2025-01-09',
    categories: ['nodejs', 'webcontainers'],
    type: 'course',
  },
];
